import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import acf, q_stat
from scipy.stats import probplot
import glob
import os
import re

# ==========================================
# 0. 配置
# ==========================================
DATA_DIR = "data"
FILE_PATTERN = os.path.join(DATA_DIR, "llm_fomc_dispersion_results_*.csv")

OUT_FIG = r"fig\fig1.6_persistence_check.png"
OUT_TAB = r"tab\Tab1.8_persistence_stats.tex"

os.makedirs(os.path.dirname(OUT_FIG), exist_ok=True)
os.makedirs(os.path.dirname(OUT_TAB), exist_ok=True)

plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman']

def load_all_models():
    files = glob.glob(FILE_PATTERN)
    df_combined = pd.DataFrame()
    for f in files:
        filename = os.path.basename(f)
        match = re.search(r'results_(.+)\.csv', filename)
        model_name = match.group(1) if match else filename
        
        try:
            df = pd.read_csv(f)
            df['date'] = pd.to_datetime(df['date']).dt.tz_localize(None).dt.normalize()
            df = df.set_index('date')[['Semantic_Dispersion']]
            df.columns = [model_name]
            if df_combined.empty: df_combined = df
            else: df_combined = df_combined.join(df, how='outer')
        except: pass
    return df_combined.sort_index().dropna()

def test_persistence(df):
    results = []
    
    for model in df.columns:
        series = df[model]
        
        # 1. AR(1) Coefficient
        # acf[0] is 1, acf[1] is lag 1
        acf_vals = acf(series, nlags=1)
        ar1 = acf_vals[1]
        
        # 2. Ljung-Box Test (Test for White Noise)
        # H0: Data is independently distributed (White Noise)
        # We test up to lag 5
        lb_stats = q_stat(acf(series, nlags=5)[1:], len(series))
        # Take the p-value at lag 5
        lb_pvalue = lb_stats[1][-1] 
        
        # 3. Standard Deviation (Volatility of the metric)
        std_dev = series.std()
        
        results.append({
            'Model': model,
            'AR(1)': ar1,
            'Ljung-Box p-val': lb_pvalue,
            'Std Dev': std_dev
        })
        
    return pd.DataFrame(results)

def plot_persistence(res_df):
    """绘制 AR(1) 系数对比图"""
    print(f"Plotting to {OUT_FIG}...")
    
    # 排序
    res_df = res_df.sort_values('AR(1)', ascending=True)
    
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # 颜色映射：根据 AR(1) 大小
    norm = plt.Normalize(res_df['AR(1)'].min(), res_df['AR(1)'].max())
    colors = plt.cm.Blues(norm(res_df['AR(1)'].values))
    
    bars = ax.barh(res_df['Model'], res_df['AR(1)'], color=colors, alpha=0.8)
    
    ax.set_xlabel('Persistence (AR(1) Coefficient)', fontsize=12)
    ax.set_title('Cognitive Memory: Persistence of Narrative Ambiguity Across Models', fontsize=14, fontweight='bold')
    
    # 标注 White Noise 区域
    # 通常 AR(1) < 0.1 接近白噪声
    ax.axvline(0.1, color='red', linestyle='--', alpha=0.5)
    ax.text(0.11, 0, 'White Noise Zone', color='red', fontsize=10, rotation=90)
    
    for i, bar in enumerate(bars):
        val = res_df.iloc[i]['AR(1)']
        pval = res_df.iloc[i]['Ljung-Box p-val']
        sig = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.1 else "(Noise)"
        ax.text(val + 0.01, bar.get_y() + bar.get_height()/2, f"{val:.2f} {sig}", va='center')

    plt.tight_layout()
    plt.savefig(OUT_FIG, dpi=300)

def generate_latex(res_df):
    print(f"Generating Table: {OUT_TAB}")
    
    latex = r"""
\begin{table}[h!]
\centering
\caption{Statistical Properties of Narrative Ambiguity Measures}
\label{tab:persistence_stats}
\begin{threeparttable}
\begin{tabular}{lccc}
\toprule
Model & Persistence ($\rho_1$) & Volatility ($\sigma$) & White Noise Test ($p$-val) \\
\midrule
"""
    for _, row in res_df.iterrows():
        # 美化模型名
        name = row['Model'].replace('_', '-')
        
        # AR1
        ar1 = f"{row['AR(1)']:.3f}"
        
        # LB P-val
        pval = row['Ljung-Box p-val']
        if pval < 0.01: p_str = "< 0.01^{***}"
        else: p_str = f"{pval:.3f}"
        
        # Decision
        if pval > 0.10: decision = "Noise"
        else: decision = "Signal"
        
        latex += f"{name} & {ar1} & {row['Std Dev']:.3f} & {p_str} \\\\\n"
        
    latex += r"""\bottomrule
\end{tabular}
\begin{tablenotes}[para,flushleft]
  \item Note: This table reports the time-series properties of $D_t$ generated by different LLMs. Persistence is measured by the AR(1) autocorrelation coefficient. The White Noise Test reports the p-value of the Ljung-Box Q-statistic at lag 5. A low p-value ($<0.05$) indicates rejection of the null hypothesis of white noise, suggesting the presence of persistent economic information.
\end{tablenotes}
\end{threeparttable}
\end{table}
"""
    with open(OUT_TAB, 'w', encoding='utf-8') as f:
        f.write(latex)

def main():
    df = load_all_models()
    if df is not None:
        stats_df = test_persistence(df)
        plot_persistence(stats_df)
        generate_latex(stats_df)
        print("Persistence Test Completed.")

if __name__ == "__main__":
    main()